#ifndef TERMINAL_CONFIG_H
#define TERMINAL_CONFIG_H

#define VGA_WIDTH 80
#define VGA_HEIGHT 20
#define VGA_ADDRESS 0xB8000
#define VGA_TEXT_WHITE_DEFAULT 0b00001111

#define MAX_TERMINAL_PREFIX_BUFF 100
#define MAX_TEMRINAL_HISTORY 100
#define MAX_INPUT_BUFFER 100
#endif